### ISSUE TITLE
License mismatch

### ISSUE THREAD

**Issue by SHPLeadingDesign** [klhengineers/RevitDeveloperTools#2]
Just wanted to give you a heads up the [LICENSE.md](https://github.com/klhengineers/RevitDeveloperTools/blob/master/LICENSE.md) file has a difference license agreement than the file headers.

https://github.com/klhengineers/RevitDeveloperTools/blob/468912b4d98e82bded3e7f6bdc773f03cfb3a8f3/KLH%20Snoop/ElementSelector.xaml.vb#L1-L8

**Comment by jdaless** [comment]
On it, thanks for the heads up!
